name: 'Get status of last workflow'
description: 'Get conclusion of last workflow run on current branch.'
branding:
  icon: 'arrow-left'
  color: 'yellow'
inputs:
  github_token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
outputs:
  last_status:
    description: "Conclusion of last workflow run on current branch"
    value: ${{ steps.set_result.outputs.last_status }}
runs:
  using: "composite"
  steps:
    - name: Get last status
      id: set_result
      uses: actions/github-script@v3.1.0
      with:
        github-token: ${{ inputs.github_token }}
        result-encoding: string
        script: |
          let workflow_id = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.run_id }}
          })
          console.log("Workflow id: " + workflow_id)

          // TODO
          let last_status = await github.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs?status=completed', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow_id
          })

          console.log("Last status: " + last_status)

          return last_status

