name: 'Get status of last workflow'
description: 'Get conclusion of last workflow run on current branch.'
branding:
  icon: 'arrow-left'
  color: 'yellow'
inputs:
  github_token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
outputs:
  last_status:
    description: "Conclusion of last workflow run on current branch"
    value: ${{ steps.last_status.outputs.last_status }}
runs:
  using: "composite"
  steps:
    - name: Get branch name
      shell: bash
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          BRANCH_NAME="${GITHUB_HEAD_REF}"
        else
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        fi

        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "Branch name: ${BRANCH_NAME}"

    - name: Get workflow id
      shell: bash
      run: |
        API_URL="${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        WORKFLOW_ID=$(
          curl --silent \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            --header 'content-type: application/json' \
            "${API_URL}" |
          sed -E -ne 's/.*"workflow_id":\s*([0-9]+).*/\1/p'
        )

        echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_ENV
        echo "Workflow id: ${WORKFLOW_ID}"

    - name: Get previous build status
      shell: bash
      id: last_status
      run: |
        API_URL="${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}"

        last_status=$(
          curl --silent \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            --header 'content-type: application/json' \
            "${API_URL}" |
          sed -E -ne 's/.*"conclusion":\s*"([^"]*)".*/\1/p' |
          head -1
        )

        echo "last_status=${last_status}" >> $GITHUB_OUTPUT
        echo "Status of the previous build: ${last_status}"
